spring.application.name=taskflow_cloud

spring.datasource.url=jdbc:mysql://terraform-20260517151812668200000001.ccfm6y6ukwhu.us-east-1.rds.amazonaws.com:3306/taskflowdb

spring.datasource.username=admin
spring.datasource.password=Taskflow123!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080